openapi: 3.0.4
info:
  title: Api Caso Médico
  description: |-
    Esto es el contrato de la api que se va a usar en este proyecto que es caso médico
  termsOfService: https://swagger.io/terms/
  version: 1.0.0
servers:
  - url: https://localhost:8000
tags:
  - name: Graphs
    description: Getting all data for the graphs
  - name: Querys
    description: How to formulate the querys calls
paths:
  /data-graph/:
    get:
      tags:   
        - Graphs
      summary: Obtener datos para una gráfica
      description: Devuelve listas de valores asociadas a dos atributos de dos modelos distintos.
      parameters:
        - name: clase_x
          in: query
          required: true
          schema:
            type: string
        - name: atributo_x
          in: query
          required: true
          schema:
            type: string
        - name: clase_y
          in: query
          required: false
          schema:
            type: string
        - name: atributo_y
          in: query
          required: false
          schema:
            type: string
        - name : clase_z
          in: query
          required: false
          schema:
            type: string
        - name: atributo_z
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Listas con valores para los ejes X, Y y opcionalmente Z
          content:
            application/json:
              schema:
                type: object
                properties:
                  ejeX:
                    type: array
                    items:
                      type: string
                  ejeY:
                    type: array
                    items:
                      type: string
                  ejeZ:
                    type: array
                    items:
                      type: string
        '400':
          description: Clase o atributo no válidos
        '405':
          description: Método HTTP no permitido
        '500':
          description: Error interno del servidor
 /api/advanced-query/:
    post:
      summary: Consulta avanzada de pacientes por condiciones anidadas
      operationId: advancedQuery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogicNode'
      responses:
        '200':
          description: Lista de job_number de pacientes que cumplen las condiciones
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_ids:
                    type: array
                    items:
                      type: string
        '400':
          description: Error en la petición
        '405':
          description: Método no permitido
        '500':
          description: Error interno del servidor
components:
  schemas:
    LogicNode:
      type: object
      required:
        - connector
        - conditions
      properties:
        connector:
          type: string
          enum: [AND, OR]
          description: Conector lógico entre condiciones o nodos
        conditions:
          type: array
          description: Lista de nodos anidados o condiciones simples
          items:
            oneOf:
              - $ref: '#/components/schemas/LogicNode'
              - $ref: '#/components/schemas/SimpleCondition'

    SimpleCondition:
      type: object
      required:
        - model
        - attribute
        - operator
        - value
      properties:
        model:
          type: string
          example: Patient
        attribute:
          type: string
          example: age
        operator:
          type: string
          enum: ["=", "!=", "<", ">", "<=", ">="]
        value:
          oneOf:
            - type: string
            - type: number
            - type: boolean