# Generated by Django 5.1.3 on 2025-03-31 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('job_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('UNKNOWN', 'UNKNOWN')], max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('report_date', models.DateField()),
                ('scale_factor', models.FloatField()),
                ('snr', models.FloatField()),
                ('msnr', models.FloatField()),
                ('qc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LateralVentricles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cm3', models.FloatField()),
                ('total_percentage', models.FloatField()),
                ('right_cm3', models.FloatField()),
                ('right_percentage', models.FloatField()),
                ('left_cm3', models.FloatField()),
                ('left_percentage', models.FloatField()),
                ('asymmetry', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Hippocampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cm3', models.FloatField()),
                ('total_percentage', models.FloatField()),
                ('right_cm3', models.FloatField()),
                ('right_percentage', models.FloatField()),
                ('left_cm3', models.FloatField()),
                ('left_percentage', models.FloatField()),
                ('asymmetry', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.patient')),
            ],
        ),
        migrations.CreateModel(
            name='GlobusPallidus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cm3', models.FloatField()),
                ('total_percentage', models.FloatField()),
                ('right_cm3', models.FloatField()),
                ('right_percentage', models.FloatField()),
                ('left_cm3', models.FloatField()),
                ('left_percentage', models.FloatField()),
                ('asymmetry', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Cerebrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cm3', models.FloatField()),
                ('total_percentage', models.FloatField()),
                ('t_gm_cm3', models.FloatField()),
                ('t_gm_percentage', models.FloatField()),
                ('t_wm_cm3', models.FloatField()),
                ('t_wm_percentage', models.FloatField()),
                ('right_cm3', models.FloatField()),
                ('right_percentage', models.FloatField()),
                ('left_cm3', models.FloatField()),
                ('left_percentage', models.FloatField()),
                ('asymmetry', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Cerebellum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cm3', models.FloatField()),
                ('total_percentage', models.FloatField()),
                ('t_gm_cm3', models.FloatField()),
                ('t_gm_percentage', models.FloatField()),
                ('t_wm_cm3', models.FloatField()),
                ('t_wm_percentage', models.FloatField()),
                ('right_cm3', models.FloatField()),
                ('right_percentage', models.FloatField()),
                ('left_cm3', models.FloatField()),
                ('left_percentage', models.FloatField()),
                ('asymmetry', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Caudate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cm3', models.FloatField()),
                ('total_percentage', models.FloatField()),
                ('right_cm3', models.FloatField()),
                ('right_percentage', models.FloatField()),
                ('left_cm3', models.FloatField()),
                ('left_percentage', models.FloatField()),
                ('asymmetry', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Amygdala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cm3', models.FloatField()),
                ('total_percentage', models.FloatField()),
                ('right_cm3', models.FloatField()),
                ('right_percentage', models.FloatField()),
                ('left_cm3', models.FloatField()),
                ('left_percentage', models.FloatField()),
                ('asymmetry', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Accumbens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cm3', models.FloatField()),
                ('total_percentage', models.FloatField()),
                ('right_cm3', models.FloatField()),
                ('right_percentage', models.FloatField()),
                ('left_cm3', models.FloatField()),
                ('left_percentage', models.FloatField()),
                ('asymmetry', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Putamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cm3', models.FloatField()),
                ('total_percentage', models.FloatField()),
                ('right_cm3', models.FloatField()),
                ('right_percentage', models.FloatField()),
                ('left_cm3', models.FloatField()),
                ('left_percentage', models.FloatField()),
                ('asymmetry', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Thalamus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cm3', models.FloatField()),
                ('total_percentage', models.FloatField()),
                ('right_cm3', models.FloatField()),
                ('right_percentage', models.FloatField()),
                ('left_cm3', models.FloatField()),
                ('left_percentage', models.FloatField()),
                ('asymmetry', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TissueMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tissue_wm_cm3', models.FloatField()),
                ('tissue_wm_percentage', models.FloatField()),
                ('tissue_gm_cm3', models.FloatField()),
                ('tissue_gm_percentage', models.FloatField()),
                ('tissue_csf_cm3', models.FloatField()),
                ('tissue_csf_percentage', models.FloatField()),
                ('tissue_brain_cm3', models.FloatField()),
                ('tissue_brain_percentage', models.FloatField()),
                ('tissue_ic_cm3', models.FloatField()),
                ('tissue_ic_percentage', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.patient')),
            ],
        ),
    ]
